 ____________________________________________________________________________
/\                                                                           \
\_| ooooooooooooooooooooooo,... ............   :oooooooooooooooooooooooooooo |
  | ooooooooooooooooooooooo.................   :oooooooooooooooooooooooooooo |
  | ooooooooooooooooooooooo... .............   ,oooooooooooooooooooooooooooo |
  | ooooooooooooooooooooooo. .......;,,''..    ,oooooooooooooooooooooooooooo |
  | ooooooooooooooooooooooo'.....,';c:cllc,.   :oooooooooooooooooooooooooooo |
  | ooooooooooooooooooool;. .......',',;cc,.     .:ooooooooooooooooooooooooo |
  | ooooooooooool:;,'...     .. ..'...''.....      ,oooooooooooooooooooooooo |
  | oooooool:,.              .. .....:',::;.       .oooooooooooooooooooooooo |
  | ooooc'.                     ...':l;;l:.         oooooooooooooooooooooooo |
  | ooo;     .                  ...:;,';:;.         :ooooooooooooooooooooooo |
  | lll.                      . ...;c::;,.. .        ..','''',:cllc:;''..':c |
  |    .'.                 .. ......';'.....  .  .                           |
  |                       ... .......'......  . .                            |
  |                        ......... . ....  ..          .         .         |
  |                          ..  ........   ..                             . |
  |                            .   .....   .        .               .        |
  |                                 ..             ...                .   .  |
  |                                              ,.                    .  .  |
  | SUCCESS: ALL YOUR DATABASE ARE BELONG TO US!                             |
  |   _______________________________________________________________________|_
   \_/_________________________________________________________________________/
