abi_type: linux_32
device_name: ubuntu_14.04
device_type: DESKTOP
firmware_version: 0.2.11
startup_file: run.sh
interfaces: 1
emulated_arch: X86_64
emulated_endianness: little
base_os: ubuntu_18.04
base_arch: X86_64
wan_access: False
vulnerable_port: 80
exploit_protocol: HTTP
exploit_port: 80
service_name: php
exploit_name: CVE-2006-0313
exploit_spec_version: 1
author: Aarno
local_privilege_required: USER
landed_privilege_level: USER
writabledir: /tmp/
exploit_interface: COMMAND_INJECTION
exploit_type: COMMAND_INJECTION
stage0Protocol: HTTP
success_probability: 99
cpe_product: cpe:2.3:a:pdfdirectory:pdfdirectory:0.2.11:*:*:*:*:*:*:*
emulation_timeout: 5
requested_test_device_type: emulated
